version: "3.8"
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DB=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/