version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DB=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ: "Asia/Seoul"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test
    depends_on:
      - db
    ports:
      - "3000:3000"
    command:
      - npm run start
    volumes:
      - ./:/app/